global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'node-exporter:9100'

  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - 'host.docker.internal:8080'